//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkWithData.ObjectsBD.baseServicesParams
{
    using System;
    using System.Collections.Generic;
    
    public partial class gateAlias
    {
        public long row_id { get; set; }
        public string alias { get; set; }
        public string FI_Check { get; set; }
        public string FO_Check { get; set; }
        public string FI_Init { get; set; }
        public string FI_Process { get; set; }
        public string FO_Process { get; set; }
        public Nullable<bool> FI_CheckNG { get; set; }
        public Nullable<bool> FO_CheckNG { get; set; }
        public Nullable<bool> FI_ProcessNG { get; set; }
        public Nullable<bool> FO_ProcessNG { get; set; }
        public string FX_Check { get; set; }
        public string FX_Process { get; set; }
        public Nullable<bool> FX_CheckNG { get; set; }
        public Nullable<bool> FX_ProcessNG { get; set; }
    }
}
